#!/usr/bin/perl -w

use strict;

my %hosts = ( celltest1 => { ip => q{18.248.4.2},
			     phones => [qw[91071403 6014736e 0a0844d8]] },
	      celltest2 => { ip => q{18.248.4.3},
			     phones => [qw[9b05f2ce f10f68e7 e819642a]] },
	      celltest3 => { ip => q{18.238.2.50},
			     phones => [qw[420733a4 9e13bef1 7e0b1626]] },
	      celltest4 => { ip => q{18.238.2.51},
			     phones => [qw[890d5903 351bc75b 3b16be3a]] } );

my @handles;

for my $hostname ( keys %hosts ) {
  my $ip = $hosts{ $hostname }{ ip };
  print STDERR "hostname: $hostname\n";
  my $port_offset = 9000 + int( rand 20000 );
  for my $phone ( @{ $hosts{ $hostname }{ phones } } ) {
    my $home_port = $port_offset + 1;
    my $lte_port = $port_offset + 2;
    open ( my $fh,
	   qq{ssh root\@$ip /home/antenna/multisend/sender/controlled-delay $ip $home_port \\`/home/antenna/multisend/measurement/getip cell-$phone\\` $lte_port cell-$phone 2>&1 |} ) or die "$!";
    $port_offset += 10;
    push @handles, $fh;
  }
}

for my $handle ( @handles ) {
  while ( my $line = <$handle> ) {
    print $line;
  }

  close $handle;
}
