#!/usr/bin/perl -w

use strict;

my $ADB = 'adb';

my %devices = ( A => '0149A97C0F012017',
		B => '014696C50601901F' );

my ( $device, @command ) = @ARGV;

die unless exists $devices{ $device };

exec { $ADB } ( 'adb', '-s', $devices{ $device }, @command );
