#!/usr/bin/perl -w

use strict;

my $ADB = '/home/antenna/android/android-sdk-linux/platform-tools/adb';

#my %devices = ( A => '0149A44C0C012007', B => '420733a4', C => '351bc75b', D => '890d5903');

my ( $device, @command ) = @ARGV;

#die unless exists $device;

exec { $ADB } ( 'adb', '-s', $device, @command );
