#!/usr/bin/perl -w

use strict;

my $ADB = '/home/keithw/android/android-sdk-linux/platform-tools/adb';

my %devices = ( A => '014696C50601901F',
		B => '0149A97C0F012017' );

my ( $device, @command ) = @ARGV;

die unless exists $devices{ $device };

exec { $ADB } ( 'adb', '-s', $devices{ $device }, @command );
